### PR TITLE
Bugfix about the reduced torque of 2FOC V 3.6 firmware

### PR DESCRIPTION
**Pull request by ale-git**
This 3.6.21 version corrects a misbehaviour in 3.6.20 so that the torque was reduced wit respect to the 3.3.x actually used in iCub and Ergocub robots. Now the torque is fine and this version is back compatible.

### CODE REVIEW

**Comment by ale-git** [comment]
@marcoaccame

**Review by valegagge — APPROVED** [review]
Finally, we get a unique fw for the robots! Great work!!!

**Comment by valegagge** [comment]
This fw has been verified on ergocub1.1. see here https://github.com/robotology/icub-firmware/issues/388

**Comment by marcoaccame** [comment]
> @marcoaccame

OK, thanks.

**Comment by ale-git** [comment]
https://github.com/robotology/icub-firmware-build/pull/103

**Pull request merged**
