### PR TITLE
amc-bldc: now the motor configuration is done on `motor_config`message reception

### PR DESCRIPTION
**Pull request by valegagge**
@ale-git and I updated the amc-bldc fw in order to configure the motor device (composed by analog, rotor encoder and PWM) in run time on `motor_config`message reception.

We tested the fw on wrist setup and it works fine.

cc @mfussi66

### CODE REVIEW

**Comment by sgiraz** [comment]
Nice done @valegagge and @ale-git! 🚀
 
Do you need to update the `robots-configuration` file as well?

**Comment by marcoaccame** [comment]
Hi, I will review the PR later in the afternoon or on Monday at most.

**Comment by valegagge** [comment]
> Nice done @valegagge and @ale-git! 🚀
> 
> Do you need to update the `robots-configuration` files as well?

yes, [here](https://github.com/robotology/robots-configuration/pull/382)

**Review by marcoaccame — APPROVED** [review]
Ok @ale-git, that is fine.

**Pull request merged**
