### PR TITLE
Update BAT-BMS protocol data. Sections: 4.5, 7.10

### PR DESCRIPTION
**Pull request by MSECode**
Update info regarding BAT service with new messages for BAT and BMS.

### CODE REVIEW

**Review by valegagge — CHANGES_REQUESTED** [review]
Hi @MSECode ,
I correct some typos and some info in the section 4.5.
Regarding the section 7.10 the sequence diagrams of start periodic message  is not correct and the sequence diagram of the  log message request is missing. We can check together f2f. 
Thanks

**Comment by valegagge** [comment]
Hi @MSECode ,

Thanks for your updates.  I checked them, and I noticed that tow changes are necessary:

1. the code of the new BMS is 18239.

2. regarding the `getlog` message, the ems sends the message to ask for the last record only once at the start-up and the BMS answers. They aren't periodic message

thanks

**Comment by MSECode** [comment]
> Hi @MSECode ,
> 
> Thanks for your updates. I checked them, and I noticed that tow changes are necessary:
> 
> 1. the code of the new BMS is 18239.
> 2. regarding the `getlog` message, the ems sends the message to ask for the last record only once at the start-up and the BMS answers. They aren't periodic message
> 
> thanks

Done. Check and let me know if it's ok.

Thanks

**Comment by valegagge** [comment]
Hi @MSECode ,
thank you now it is ok!
you just forgot to add the code of the new  in the section `7.10.4	Stop of BAT service`.

After that change, we can merge the PR

**Comment by valegagge** [comment]
Hi @MSECode , 
I just noticed that the table of contents is not updated. 
image

Please update it . thanks

**Review by valegagge — APPROVED** [review]
LGTM

**Pull request merged**
