### PR TITLE
AMCx mbd: codegen R2024a from icub-fw-models c8834b2

### PR DESCRIPTION
**Pull request by mfussi66**
This PR updates the MBD code for the AMCBLDC and AMC boards up to the commit: https://github.com/robotology/icub-firmware-models/commit/c8834b2c166b07e731f038a21ca9ba5d8a7035d2

Highlights of this release are in the following PRs:

- https://github.com/robotology/icub-firmware-models/pull/62
- https://github.com/robotology/icub-firmware-models/pull/68 **Applies also to AMC and AMCBLDC**
- https://github.com/robotology/icub-firmware-models/pull/96

Integration tests on a single setup and on the robot are performed in
- https://github.com/robotology/icub-firmware-models/issues/92
- https://github.com/robotology/icub-firmware-models/issues/95

I updated the minor versions of amc2c and amcbldc, and reset the revision to zero.

### CODE REVIEW

**Comment by marcoaccame** [comment]
> I updated the minor versions of amc2c and amcbldc, and reset the revision to zero.

OK, as the minor number changes when we have the new binaries we shall need to update also the xml files in robots-configuration.

**Review by marcoaccame — COMMENTED** [review]
Hi @mfussi66, it seems fine. I assume you have done the required test, correct?

If so, we can merge.

**Comment by mfussi66** [comment]
> Hi @mfussi66, it seems fine. I assume you have done the required test, correct?
> 
> If so, we can merge.

The tests are linked in the PR body, both performed on single motors and on the robot.

**Comment by mfussi66** [comment]
> > > I updated the minor versions of amc2c and amcbldc, and reset the revision to zero.
> > 
> > 
> > OK, as the minor number changes when we have the new binaries we shall need to update also the xml files in robots-configuration.
> 
> I increased the amc2c version from 3.0.4 to 3.2. That was a mistake since the amc2c is independent from the left or right decoupler. I'll change it to 3.1.

Fixed this @marcoaccame . If that's ok to you we can merge.

**Review by marcoaccame — APPROVED** [review]
OK, thanks

**Pull request merged**
