### PR TITLE
CAN protocol for MC: reviewed document + `embot::prot::can::motor` 

### PR DESCRIPTION
**Pull request by marcoaccame**
This PR realigns the CAN protocol used in modern motor boards such as `foc`, `amcbldc`, `amc.mot` aka `amc2c` and soon `amcfoc.mot`. 

As such it corrects (and implemented where missing) messaging data structures in `embot::prot::can::motor` and corrects the related CAN protocol document.

The changes have been verified w/ existing boards and are of no effect because the new data structures will be used for the `amcfoc.mot` board.

### CODE REVIEW

**Comment by valegagge** [comment]
Hi @marcoaccame ,
I had a very quick look at the changes. Only to understand correctly, are the new boards compatible with the legacy CAN protocol? I mean the one that the 2foc implements. In addition, do new boards implement new messages for additional info?

Thanks in advance

**Comment by marcoaccame** [comment]
> Hi @marcoaccame , I had a very quick look at the changes. Only to understand correctly, are the new boards compatible with the legacy CAN protocol? I mean the one that the 2foc implements. In addition, do new boards implement new messages for additional info?
> 
> Thanks in advance

Hi @valegagge, I have updated the .doc so, pls have a look at that for further clarifications. 

But in short, there are no changes in what the `foc` board uses and how the `amcbldc` and `amc` boards behave, because:

> The changes have been verified w/ existing boards and are of no effect because the new data structures will be used for the `amcfoc.mot` board.


So:
- the .doc documents the protocol used by `foc` board and clarifies it. No changes in existing protocol.
- the .h and .cpp implement the messages described in the .doc but they are not used yet by the `amcfoc`, and not used by `amcbldc` and `amc`.


>  In addition, do new boards implement new messages for additional info?

If w/ `additional info` you mean the new streaming MC message that you recently added to transport the temperature from the `foc` board, then ... the .h and .cpp support it, but the `amcbldc` and `amc` has never supported that. So, nothing has changed.

**Comment by marcoaccame** [comment]
I will keep this PR in draft form for a a couple of days because I want to verify if the CAN messaging provided by this PR is sufficient for use by the `amcfoc.mot` application that is WIP in another branch.

**Comment by marcoaccame** [comment]
> I will keep this PR in draft form for a a couple of days because I want to verify if the CAN messaging provided by this PR is sufficient for use by the `amcfoc.mot` application that is WIP in another branch.

I have verified and I believe that the cleaning of `embot::prot::can::motor` is OK for the need of the `amcfoc.mot`.

**Comment by valegagge** [comment]
> If w/ additional info you mean the new streaming MC message ADDITIONAL_STATUS that you recently added to transport the temperature from the foc board, then:

the amcbldc and amc use MBD encoding / decoding and don't have this message;
the .h and .cpp of this PR support it and the amcfoc board may be able to transmit it.

no, I was meaning if it was necessary to add new messages for new information. 

Thanks for the answer.

**Pull request merged**
