### PR TITLE
fix euler angles

### PR DESCRIPTION
**Pull request by davidetome**
This PR fixes the Euler angles representation for `RFE ` / `MTB4 `/  `MTB4C` and for `STAIN2 `/ `STRAIN2C`

### CODE REVIEW

**Comment by davidetome** [comment]
Wainting a positive on STRAIN2 fix before merge this 👍🏻

**Review by marcoaccame — COMMENTED** [review]
OK @davidetome, thanks. With a quick look it seems OK. I will review it when you give me the go after the feedback of the users.

**Comment by davidetome** [comment]
fix done

cc @marcoaccame @Nicogene @pattacini

**Comment by marcoaccame** [comment]
Hi @davidetome, thanks. we can merge

**Pull request merged**
