### PR TITLE
[WIP] Implement a static model with Stiction/Stribeck, Coulomb and Viscous components

### PR DESCRIPTION
**Pull request by nunoguedelha**
These changes are the implementation of https://github.com/dic-iit/element_torque-control-via-current/issues/81 and a dependency of https://github.com/robotology/robots-configuration/pull/122.

### CODE REVIEW

**Comment by nunoguedelha** [comment]
CC @DanielePucci

**Comment by DanielePucci** [comment]
CC @marcoaccame @ale-git @S-Dafarra

**Comment by S-Dafarra** [comment]
I am actually interested in commit https://github.com/robotology/icub-firmware/pull/101/commits/3f1b6d33357c7b6c8ce96cc455dd79cb7e45cd33 since we are having a problem with F/T https://github.com/robotology/icub-tech-support/issues/854, causing several demo failures.

**Comment by marcoaccame** [comment]
You tested the changes on iCubGenova04, did you not? Can you please build binaries and test also for mc4plus?

**Comment by marcoaccame** [comment]
then: @ale-git would you please have a look at the changes proposed in motor control files, as you wrote them?

**Comment by ale-git** [comment]
Hi @marcoaccame it seems fine with me.

**Comment by nunoguedelha** [comment]
> because value 103 is used only to recognise a wip or debug application.

Hi @marcoaccame . Sure, as we discussed afterwards F2F, I still had tests to run on the robot (iCubGenova04), for that reason I left [WIP] in the PR description. Sorry if it was not clear.

> Moreover,
> the increment of minor version and date are needed also for `mc4plus` and `mc2plus` boards.

I will update the versions accordingly after the tests and check with @ale-git .

> You tested the changes on iCubGenova04, did you not? Can you please build binaries and test also for mc4plus?

Sure. Is the building environment for mc4plus the same as for the EMS? If not, I will either need a license or ask @ale-git to build the binaries for me after the tests on the EMS boards.

**Comment by nunoguedelha** [comment]
This branch has been tested on iCubGenova04:
- on `yarpmotorgui` in torque control mode with current output, on individual joints (legs, torso)
- running the Simulink model https://github.com/robotology/whole-body-controllers/blob/master/controllers/fixed-base-joints-control/jointsControl.mdl with the robot on the pole.

**We should wait for https://github.com/robotology/yarp/pull/2115 to be ready for merge before merging this PR.**

**Comment by nunoguedelha** [comment]
@ale-git , @marcoaccame , what is the policy for incrementing the firmware Major/Minor versions?

**Comment by marcoaccame** [comment]
Hi @nunoguedelha, you just need to increase the minor number

**Comment by marcoaccame** [comment]
having talked w/ @ale-git we can close this old PR which has been in [WIP] state for long. i shall keep the branch for some more time however. cc @nunoguedelha

**Comment by DanielePucci** [comment]
CC @GiulioRomualdi @isorrentino @giovannipizzolante

**Comment by nunoguedelha** [comment]
Hi @marcoaccame , thank you for the heads up. I'm reviewing my pld branches now to make sure they are pushed to my fork. It is worth keeping at least `feature/impl-static-friction-comp-rebase` in the robotology `icub-firmware` repo as it had some developments worth integrating soon enough. I need to discuss with the team to figure out the proper plan to address this, as I don't have the bandwidth right now to address it myself.
we'll get back to you ASAP.

**Comment by marcoaccame** [comment]
hi @nunoguedelha pls ping me when you have any news about how to proceed

**Pull request closed without merging**
