### PR TITLE
Fix FT IMU frames conversion

### PR DESCRIPTION
**Pull request by pattacini**
This PR fixes a problem we spotted in the conversion between the FT reference frame and the frame of the mounted IMU.

⚠️ I've replaced tabs w/ spaces too.

Ref: https://github.com/icub-tech-iit/documentation/pull/212

cc @davidetome @simeonedussoni @marcoaccame

### CODE REVIEW

**Comment by pattacini** [comment]
For a better back-to-back review: https://github.com/robotology/icub-firmware/pull/274/files?diff=split&w=1.

**Comment by traversaro** [comment]
fyi @isorrentino

**Comment by traversaro** [comment]
fyi @isorrentino

**Comment by pattacini** [comment]
Merging anyway as it's a localized fix.

**Pull request merged**
