### PR TITLE
Workaround to manage the MC4+ 16 bit encoder overflow/reset.

### PR DESCRIPTION
**Pull request by ale-git**

### CODE REVIEW

**Comment by maggia80** [comment]
@ale-git I think that the issue is in the division for `o->GEARBOX`. We tested on the robot that when we set this to `1` the motor position output works as expected.

**Comment by ale-git** [comment]
@maggia80 yes but, with this version or the standard one?

**Comment by maggia80** [comment]
the standard one

**Comment by valegagge** [comment]
Is this PR connected to a ticket or any issue?

**Comment by maggia80** [comment]
https://github.com/icub-tech-iit/project-ergocub/issues/77

**Comment by maggia80** [comment]
https://github.com/icub-tech-iit/proto/issues/1738#issuecomment-1196683652

**Comment by pattacini** [comment]
@valegagge, you should be able to see here the cross-links to our internal issues.

**Comment by valegagge** [comment]
After @ale-git aligned his branch to devel, @MSECode and I tested the fix on the ecub hand setup on bench.

As you can see from the following image, the rotor positions had jumps during the motion.

MicrosoftTeams-image (3)


Using the fw with the overflow fixed, the rotor positions have any jumps.

MicrosoftTeams-image (4)

The PR could be merged.  🥳 
@marcoaccame 

As is mentioned [here](https://github.com/icub-tech-iit/project-ergocub/issues/77#issuecomment-1322199878), on cm4plus two of the 4 motor ports are connected to 16 bits registry. This course the overflow. Now, in the @ale-git PR, it is fixed.

**Comment by valegagge** [comment]
@sgiraz 
please also check the correct value of encoder, because @davidetome [here ](https://github.com/icub-tech-iit/project-ergocub/issues/77#issuecomment-1322199878) said that the `encoder` pram has been changed!

**Review by marcoaccame — APPROVED** [review]
ok

**Comment by valegagge** [comment]
Executable file updated here: https://github.com/robotology/icub-firmware-build/pull/68.

**Version 3.63**

**Pull request merged**
